name: Blacken

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  blacken:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.ACTION_TOKEN }}
        ref: ${{ github.head_ref }}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - uses: actions/cache@v2
      id: cache
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ runner.os }}-python-${{ env.pythonLocation }}-black
    - name: Install Black
      if: steps.cache.outputs.cache-hit != 'true'
      run: pip install black
    - name: Black Check
      run: black --check .
    - name: Black Format
      if: failure()
      run: |
        black .
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com
        git add *.py
        git commit -m "ðŸŽ¨ Format Python code with Black"
        git push
